<a href="https://colab.research.google.com/github/zulya9090/KbdLab/blob/main/11.deep/d0714/02_%EB%94%A5%EB%9F%AC%EB%8B%9D_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## keras 딥러닝 - mnist

In [ ]:
import sklearn
from tensorflow import keras
from sklearn.linear_model import SGDClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
# 데이터 불러오기
(train_data,train_label),(test_data,test_label) = (keras.datasets.fashion_mnist.load_data())

In [ ]:
# 데이터 전처리
# 1) 데이터 확인 - pandas : info,describe
train_data.shape # (60000, 28, 28)

(60000, 28, 28)

In [ ]:
train_label.shape # (60000, 28, 28)

(60000,)

In [ ]:
# 2) class 확인 - pandas : 컬럼, 클래스
np.unique(train_label,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000]))

In [ ]:
# 정규화, 표준화 작업
train_scaled = train_data/255.0
test_scaled = test_data/255.0

In [ ]:
train_scaled = train_scaled.reshape(-1,28*28)
test_scaled = test_scaled.reshape(-1,28*28)

In [ ]:
# train_data,test_data,val_data
sub_data,val_data,sub_label,val_label = train_test_split(train_scaled,train_label)

In [ ]:
# 클래스 개수 - 10
np.unique(train_label)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
# 1. 딥러닝 선언
# keras 입력층 클래스 개수와 같아야 함. 
# 클래스가 여러개, softmax사용 1개일때는 sigmoid함수
# 출력층
dense = keras.layers.Dense(100,activation='sigmoid',input_shape=(784,))
dense2 = keras.layers.Dense(10,activation='softmax')
# 알고리즘선언
model = keras.Sequential(dense,dense2)
# 설정 - 이진분류 : sparse_binary_crossentropy accuracy : 정확도 출력
model.compile(loss='sparse_categorical_crossentropy', metrics='accuracy')

In [ ]:
# 2. 딥러닝 선언
# keras 입력층 클래스 개수와 같아야 함. 
# 클래스가 여러개, softmax사용 1개일때는 sigmoid함수
# 출력층

# 알고리즘선언
model = keras.Sequential([
        keras.layers.Dense(100,activation='sigmoid',input_shape=(784,)),
        keras.layers.Dense(10,activation='softmax')
])
# 설정 - 이진분류 : sparse_binary_crossentropy accuracy : 정확도 출력
model.compile(loss='sparse_categorical_crossentropy', metrics='accuracy')

In [ ]:
# 3. 딥러닝 선언 
# 알고리즘 선언
model = keras.Sequential()
model.add(keras.layers.Dense(100,activation='sigmoid',input_shape=(784,)))
model.add(keras.layers.Dense(10,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy',metrics='accuracy')

In [ ]:
# 훈련 - 2차원데이터
model.fit(train_scaled,train_label,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5370 - accuracy: 0.8133
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3947 - accuracy: 0.8583
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3603 - accuracy: 0.8701
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3396 - accuracy: 0.8775
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3222 - accuracy: 0.8850


In [ ]:
# 정확도
score = model.evaluate(test_scaled,test_label)
score

313/313 [==============================] - 1s 2ms/step - loss: 0.3636 - accuracy: 0.8729


[0.36359938979148865, 0.8729000091552734]